<h4><span class="color_magenta"><?=$this->country["name"];?></span>.</h4>

<div class="grid_5 alpha">
<form method="post">
	<input type="hidden" name="operation" value="rename"/>
    <label for="country">New name</label><br/>
	<input type="text" name="country" value="<?=$this->country["name"];?>"/>
	<input type="submit" name="rename" value="Rename" class="button" />
</form>
</div>

<div class="grid_3">
<form method="post">
	<input type="hidden" name="operation" value="delete"/>
    <label for="delete">Delete</label><br/>
	<input type="submit" name="delete" value="Confirm" class="button" />
</form>
</div>


<div class="clear"></div>

<div class="grid_11 top_40 alpha">

<h4>Locations</h4>
<ul class="left-menu">
<?php
$i = 0;
if (isset($this->country["places"]) && count($this->country["places"])>0) {

foreach ($this->country["places"] as $place) {
	$i++;
	if ($i%2 == 0) {
		$class="odd";
	} else {
		$class="even";
	}
	?>
	<li class="<?=$class;?>"><a href="/admin/destinations/locations/id/<?=$place["id"];?>"><?=$place["name"];?></a></li>
	<?php
}

} else {
	echo "<li>None found.</li>";
}
?>
</ul>

</div>
