<h4><span class="color_magenta"><?=$this->place["name"];?>, <?=$this->country["name"];?></span>.</h4>

<div class="grid_3 alpha">
<form method="post">
	<input type="hidden" name="operation" value="rename"/>
    <label for="country">New name</label><br/>
	<input type="text" name="place" value="<?=$this->place["name"];?>"/>
	<input type="submit" name="rename" value="Rename" class="button" />
</form>
</div>

<div class="grid_3">
<form method="post">
	<input type="hidden" name="operation" value="move"/>
    <label for="country">Move to another country</label><br/>
    <select name="country">
    	<?php
    		foreach ($this->allCountries as $country) {
    			if ($country["id"] == $this->country["id"]) {
    				$selected = "selected = 'selected'";
    			} else {
    				$selected = "";
    			}
    			echo "<option ".$selected." value='".$country["id"]."'>".$country["name"]."</option>";
    		}
    	?>
    </select>
	<input type="submit" name="move" value="Move location" class="button" />
</form>
</div>

<div class="grid_3">
<form method="post">
	<input type="hidden" name="operation" value="delete"/>
    <label for="delete">Delete</label><br/>
    <div style="margin-top:41px;">
	<input type="submit" name="delete" value="Confirm" class="button" />
	</div>
</form>
</div>


<div class="clear"></div>

<div class="grid_11 top_40 alpha">

<h4>All locations from <?=$this->country["name"];?></h4>
<ul class="left-menu">
<?php
$i = 0;
if (isset($this->country["places"])) {

foreach ($this->country["places"] as $place) {
	$i++;
	if ($i%2 == 0) {
		$class="odd";
	} else {
		$class="even";
	}
	?>
	<li class="<?=$class;?>"><a href="/admin/destinations/locations/id/<?=$place["id"];?>"><?=$place["name"];?></a></li>
	<?php
}

} else {
	echo "<li>None found.</li>";
}
?>
</ul>

</div>
