<h4>Welcome to my*republic - a <span class="color_magenta">visual guide</span> for the places you've seen.</h4>
<div class="top_20"></div>
<img src="/images/content/front.jpg"/>
<h1 class="top_20">more like <span class="color_magenta">flickr</span> but with <span class="color_blue_dark">big images</span> and <span class="color_green">fullscreen.</span></h1>
<h6>Start exploring and discover beautiful destinations. Be our guide and share your opinions.</h6>
