<?php

//dummy file to be used by poedit

$this->t("index");
$this->t("news");
$this->t("recommendation");
$this->t("request");
$this->t("about-us");
$this->t("termeni");
$this->t("January");
$this->t("February");
$this->t("March");
$this->t("April");
$this->t("May");
$this->t("June");
$this->t("July");
$this->t("August");
$this->t("September");
$this->t("October");
$this->t("November");
$this->t("December");
$this->t("photos");
$this->t("forum");
$this->t("partners");
$this->t("article");
$this->t("author");
$this->t("categories");
$this->t("usage");
$this->t("projects");
