<div class="cA column noprint" id="cA">
		
		<ul class="menu">
			<li>
			<strong>Cache</strong>
			</li>
		</ul>		
		
		<hr class="largeBreak"/>
</div>
			
<hr class="noscreen noprint" />
			
<div class="cB column">
	
	<div class="content-inner-left">

				<ul id="tabs_example_one" class="subsection_tabs">  
				    <li class="tab"><a href="#lista">Website republicat</a></li>  
				</ul>  
				
				<div id="lista">
					<br/>

					Paginile din cache au fost sterse<br/>
					La prima vizita se vor regenera in mod automat.<br/><br/>
					
					Click <a href="/">aici</a> pentru a vizita prima pagina.
					
					<div class="separator-nomargin"><hr/></div>
										
				</div>
		
	</div><!-- content-inner-left -->

</div><!-- cB column -->
