<h4>Change my password.</h4>
<?php echo $this->render('my-account/submenu-notlogged.phtml'); ?>	

<?php if(!empty($this->message)) :?>
<h6><?php echo $this->escape($this->message);?></h6>
<?php endif; ?>	

<div class="clear"></div>

<form action="<?php echo $this->l("my-account","change-password");?>" method="post">
<input type="hidden" name="mail" value="<?php echo $this->mail;?>"/>
<input type="hidden" name="code" value="<?php echo $this->code;?>"/>

<label for="password">New password</label><br/>
<input type="password" name="password" value=""/>

<div class="clear"></div>

<label for="confirm">Confirm password</label><br/>
<input type="password" name="confirm" value=""/>

<div class="clear"></div>

<input type="submit" name="login" value="<?php echo $this->t("Change password");?>" class="button" />

</form>
