<h4>My favorite places.</h4>
<?php echo $this->render('my-account/submenu-logged.phtml'); ?>	

<?php
for ($i=0;$i<count($this->myCountries);$i++) {
$country = $this->myCountries[$i];
?>

<div class="grid_3 alpha right_40">
	
	<ul class="left-menu">
		<?php

		echo '<li class="title">'.$country["name"].'</li>';

		foreach ($country["places"] as $place) {
	
			$contentArray = array();
			$contentArray[$this->language] = array();
			$contentArray[$this->language]["body"] 	= $place["name"];
			$contentArray[$this->language]["id"] 	= $place["id"];
			$contentLink = $this->l("destinations","index",$contentArray)."?f=".$this->userID;
			echo '<li><a href="'.$contentLink.'">'.$place["name"].'</a></li>';
		}
		?>
	</ul>
	
</div>

<?php
}
?>
