<h4>Recover your password.</h4>
<?php echo $this->render('my-account/submenu-notlogged.phtml'); ?>	

<?= $this->t("Un cod de autentificare pentru schimbarea parolei curente a fost trimis la adresa specificata.");?><br/>
<?= $this->t("Verificati-va contul (inclusiv folderele bulk/spam) si procedati conform instructiunilor.");?>
<br/><br/>
Click <a href="<?=$this->l();?>"><?= $this->t("aici");?></a> <?= $this->t("pentru a reveni la prima pagina.");?>
