<h4>About the project.</h4>
<div class="top_20"></div>
Not much text as this place is about places and photos. <br/><br/>You all have cool cameras. Still though, most images found on the Internet are only small thumbnails. Besides that it's a pain to find them. Before allowing your cd's to gather dust please select some cute travel photos and share them with us. We'd love to check out new places every day and also you'd have quick access to your organized photo collection anytime. We're also getting out a Wordpress plugin so that you'd be able to show your photos inside any blog you like. Yay. 
<br/><br/>
Thank you and enjoy your stay here.