<?php

	$contentArrayC = array();
	$contentArrayC[$this->language] = array();
	$contentArrayC[$this->language]["body"] 	= $this->activeCountry["name"];
	$contentArrayC[$this->language]["id"] 		= $this->activeCountry["id"];

?>

	<span><a title="Browse all destinations from <?=$this->activeCountry["name"];?>" href="<?php echo $this->l("countries","index",$contentArrayC);?>">Destinations</a></span> / 
	<span><a title="Travel opinions on <?=$this->activeCountry["name"];?>" href="<?php echo $this->l("countries","opinions",$contentArrayC);?>">Travel opinions</a></span> / 

	<div class="clear top_20"></div>