<?php

function getLink($queryParams,$params) {

$url = "/admin/comentarii?";
$parameters = array();
foreach ($queryParams as $key=>$value) {
	if (strtolower($key) != "page") $parameters[] = $key."=".$value;
}
foreach ($params as $key=>$value) {
	$parameters[] = $key."=".$value;
}
$url .= join("&",$parameters);
return $url;

}

?>
<div id="paginationControl">
Comentarii <?= $this->firstItemNumber; ?> - <?= $this->lastItemNumber; ?> din <?= $this->totalItemCount; ?> | 

<a href="<?= getLink($this->query,array('page' => $this->first)); ?>">prima pagina</a> | 

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?= getLink($this->query,array('page' => $this->previous)); ?>">inapoi</a> |
<?php else: ?>
  <span class="disabled">inapoi</span> |
<?php endif; ?> 

<?php
foreach ($this->pagesInRange as $page) {
?>
<?php
if ($this->current != $page) {
?>
	<a href="<?= getLink($this->query,array('page' => $page)); ?>"><?= $page; ?></a> 
<?php	
} else {
	echo $page;
}
}

if ($this->lastPageInRange < $this->last) {

	echo ".. ";
?>	
	<a href="<?= getLink($this->query,array('page' => $last)); ?>"><?= $this->last; ?></a>
<?
}

?>

 | 

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?= getLink($this->query,array('page' => $this->next)); ?>">inainte</a> |
<?php else: ?>
  <span class="disabled">inainte</span> |
<?php endif; ?>

<a href="<?= getLink($this->query,array('page' => $this->last)); ?>">ultima pagina</a><br/>

</div>
