<h4>Locations.</h4>

<ul class="left-menu">
<?php
$i = 0;
foreach ($this->countries as $country) {
	$i++;
	if ($i % 2 == 0) {
		$class="odd";
	} else {
		$class="even";
	}
	echo '<li class="'.$class.'"><a class="subactive" href="/admin/photos/locations/country/'.$country["id"].'">'.$country["name"].'</a>';
	if (count($country["places"]) > 0) {
		echo ' ( ';
		foreach ($country["places"] as $place) {
			echo '<a href="/admin/photos/locations/destination/'.$place["id"].'">'.$place["name"].'</a> ';
		}
		echo ' )';
	}
	echo "</li>";
	echo "<div class='clear'></div>";
}
?>
</ul>
