<div class="full_length height_100 top_40" id="footer" style="background:#f6f6f6;">

	<div class="container_16">

		<div class="grid_16 top_20">&nbsp;</div>
		
		<div class="clear"></div>
	
		<div class="grid_5">&nbsp;</div>
		<div class="grid_11">my*republic is a project by <a href="http://www.nouauzina.ro">noua uzina</a> &copy; 2007-<?=date('Y');?></div>
		
		<div class="clear"></div>

	</div>
</div>
