<div class="clear"></div>
<div class="footer">
	<div class="container_16">
		<div class="top"></div>
		<div class="clear"></div>
		<div class="grid_16 credentials">
			<center>
				my*republic is a project by <a href="http://www.nouauzina.ro">noua uzina</a> &copy; 2007-<?=date('Y');?>
			</center>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
<br/>
